# nodes/auto/generate_search_query_node.py
import json
from graph.state import AutoState
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
from prompts.auto.query_generator import QUERY_GENERATOR_PROMPT
from memory.search_schema import SearchIntentProfile

llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.4)
# Force strict structural layout matching our intent parameters
structured_query_generator = llm.with_structured_output(SearchIntentProfile)

def generate_search_query_node(state: AutoState):
    """
    Auto Pipeline Layer: Analyzes the week's operational context overview 
    and generates precise, targeted search goals for the internet and code ecosystems.
    """
    print("🌙 Auto Pipeline: Formulating intelligence search intents and hackathon monitoring targets...")

    # 1. Fetch the compiled briefing generated by the previous auto_context_node
    retrieved_list = state.get("retrieved_context") or []
    
    # Locate our context block from the array
    context_briefing = ""
    for item in retrieved_list:
        if "[Auto System Operational Context]" in item:
            context_briefing = item
            break
            
    if not context_briefing:
        context_briefing = "Fallback Context: User is actively exploring full-stack engineering and competitive hackathons."

    # 2. Invoke our structured query architect
    intent_profile = structured_query_generator.invoke([
        SystemMessage(content=QUERY_GENERATOR_PROMPT),
        HumanMessage(content=f"Review this compiled summary context block:\n\n{context_briefing}")
    ])

    print(f"🎯 Query Generator: Extracted {len(intent_profile.web_queries)} Web Queries and {len(intent_profile.github_targets)} GitHub tracking tasks.")

    # 3. Save the search queries into a tracking string in state so search_node can consume it cleanly
    # We join them or overwrite the state user_query dynamically for downstream processing
    primary_query = intent_profile.web_queries[0] if intent_profile.web_queries else "Smart India Hackathon updates"

    return {
        "user_query": primary_query,
        "final_response": f"Generated Search Targets:\nWeb: {json.dumps(intent_profile.web_queries)}\nGit: {json.dumps(intent_profile.github_targets)}"
    }